### ISSUE TITLE
Slideshow template install errors

### ISSUE THREAD

**Issue by raesene** [slideshow-s9/slideshow#1]
I've just installed slideshow and I'm getting some errors installing templates.

installed versions

```
gem list slideshow

*** LOCAL GEMS ***

slideshow (3.0.1)
slideshow-models (3.0.1)
slideshow-templates (3.0.0)
```

if I try any install commands, e.g. slideshow install impress.js I'm getting 404 errors on download

```
slideshow install impress.js
confutils/1.1.2 on Ruby 2.2.1 (2015-02-26) [x86_64-linux]
logutils/0.6.1 on Ruby 2.2.1 (2015-02-26) [x86_64-linux]
fetcher/0.4.5 on Ruby 2.2.1 (2015-02-26) [x86_64-linux]
textutils/1.4.0 on Ruby 2.2.1 (2015-02-26) [x86_64-linux]
slideshow-models/3.0.1 on Ruby 2.2.1 (2015-02-26) [x86_64-linux]
slideshow-templates/3.0.0 on Ruby 2.2.1 (2015-02-26) [x86_64-linux]
slideshow/3.0.1 on Ruby 2.2.1 (2015-02-26) [x86_64-linux]
Slide Show (S9) v3.0.1 on Ruby 2.2.1 (2015-02-26) [x86_64-linux]
  Mapping fetch shortcut 'impress.js' to: https://raw.github.com/slideshow-templates/slideshow-impress.js/master/impress.js.txt,https://raw.github.com/slideshow-templates/slideshow-impress.js/master/impress.js.txt.quick
Fetching template pack 'impress.js'
    from 'https://raw.github.com:443/slideshow-templates/slideshow-impress.js/master'
    saving to '/home/rorym/.slideshow/templates/impress.js'
  Downloading manifest 'impress.js.txt'...
*** error - fetch HTTP - 404 Not Found

*** error: Not Found
```
with ``` --verbose ``` enabled I get a URL of 

```
[debug] GET /slideshow-templates/slideshow-impress.js/master/impress.js.txt uri=https://raw.githubusercontent.com/slideshow-templates/slideshow-impress.js/master/impress.js.txt, redirect_limit=4
*** error - fetch HTTP - 404 Not Found
```
manually checking for that URL in a browser gets a 404 as well..

**Comment by geraldb** [comment]
Thanks for reporting. Will get fixed with the next update. The bundled (built-in) index is not up-to-date. Use:

$ slideshow update

and retry. It will work now. Cheers.

**Comment by raesene** [comment]
cool that worked great, Thanks :)

**Comment by nightscape** [comment]
I'm getting that error again. Running `slideshow update` does not fix it...
Anything else I can do?

**Comment by geraldb** [comment]
@nightscape FYI: Thanks for reporting. Will look into it tomorrow (Thursday).    Cheers. PS: Can you let me know what package you try to install e.g. impress.js or another one (e.g. deck.js, reveal.js etc.)?

**Comment by nightscape** [comment]
I created a Pull Request here: https://github.com/slideshow-s9/registry/pull/1
